name: over-bot
dependencies:
- openssl=1.0.2h=1
- pip=8.1.2=py35_0
- python=3.5.1=0
- readline=6.2=2
- setuptools=23.0.0=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- zlib=1.2.8=3
- pip:
  - aiohttp==0.21.6
  - blinker==1.4
  - cffi==1.6.0
  - chardet==2.3.0
  - click==6.6
  - decorator==4.0.10
  - discord.py==0.10.0a0
  - flask==0.11.1
  - flask-mail==0.9.1
  - flask-sqlalchemy==2.1
  - flask-whooshalchemy==0.56
  - flask-wtf==0.12
  - itsdangerous==0.24
  - jinja2==2.8
  - markupsafe==0.23
  - pbr==1.10.0
  - pycparser==2.14
  - pynacl==1.0.1
  - six==1.10.0
  - sqlalchemy==1.0.13
  - sqlalchemy-migrate==0.10.0
  - sqlparse==0.1.19
  - tempita==0.5.2
  - websockets==3.1
  - werkzeug==0.11.10
  - whoosh==2.7.4
  - wtforms==2.1

